export const CREATE_POST = 'CREATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const LIKE_POST = 'LIKE_POST'
export const COMMENT = 'COMMENT'
export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_POST = 'FETCH_POST'
export const FETCH_POSTS_BY_SEARCH = 'FETCH_POSTS_BY_SEARCH'

export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'

export const SHOW_SKELETON = 'SHOW_SKELETON'
export const HIDE_SKELETON = 'HIDE_SKELETON'
export const SHOW_SPINNER = 'SHOW_SPINNER'
export const HIDE_SPINNER = 'HIDE_SPINNER'
